import {
  completeFromList,
  type Completion,
  type CompletionSource,
} from "@codemirror/autocomplete";

/**
 * Curated list of PostgreSQL functions surfaced by autocomplete.
 *
 * Drawn from the PostgreSQL 17 docs — Chapters 9 (Functions) and 20
 * (System Information). Covers aggregates, windows, JSON/JSONB,
 * date/time, string, regexp, array, math, and common system helpers.
 *
 * The built-in PostgreSQL dialect shipped by `@codemirror/lang-sql`
 * treats most of these as generic keywords (if at all). This list lets
 * us render them as functions and auto-insert `(` on completion.
 */
export const POSTGRES_FUNCTIONS: readonly string[] = Object.freeze([
  // Aggregate
  "array_agg",
  "avg",
  "bit_and",
  "bit_or",
  "bool_and",
  "bool_or",
  "count",
  "every",
  "json_agg",
  "jsonb_agg",
  "json_object_agg",
  "jsonb_object_agg",
  "max",
  "min",
  "mode",
  "range_agg",
  "range_intersect_agg",
  "string_agg",
  "sum",
  "xmlagg",
  // Statistical aggregates
  "corr",
  "covar_pop",
  "covar_samp",
  "regr_avgx",
  "regr_avgy",
  "regr_count",
  "regr_intercept",
  "regr_r2",
  "regr_slope",
  "regr_sxx",
  "regr_sxy",
  "regr_syy",
  "stddev",
  "stddev_pop",
  "stddev_samp",
  "variance",
  "var_pop",
  "var_samp",
  // Ordered-set aggregates
  "percentile_cont",
  "percentile_disc",
  "rank",
  "dense_rank",
  "percent_rank",
  "cume_dist",

  // Window functions
  "row_number",
  "ntile",
  "lag",
  "lead",
  "first_value",
  "last_value",
  "nth_value",

  // JSON / JSONB
  "to_json",
  "to_jsonb",
  "row_to_json",
  "json_array",
  "jsonb_array",
  "json_object",
  "jsonb_object",
  "json_build_array",
  "jsonb_build_array",
  "json_build_object",
  "jsonb_build_object",
  "json_array_length",
  "jsonb_array_length",
  "json_each",
  "jsonb_each",
  "json_each_text",
  "jsonb_each_text",
  "json_object_keys",
  "jsonb_object_keys",
  "json_extract_path",
  "jsonb_extract_path",
  "json_extract_path_text",
  "jsonb_extract_path_text",
  "json_array_elements",
  "jsonb_array_elements",
  "json_array_elements_text",
  "jsonb_array_elements_text",
  "jsonb_set",
  "jsonb_set_lax",
  "jsonb_insert",
  "jsonb_strip_nulls",
  "jsonb_path_exists",
  "jsonb_path_match",
  "jsonb_path_query",
  "jsonb_path_query_array",
  "jsonb_path_query_first",
  "jsonb_pretty",
  "jsonb_typeof",
  "json_typeof",

  // Date / time
  "age",
  "clock_timestamp",
  "current_date",
  "current_time",
  "current_timestamp",
  "date_add",
  "date_bin",
  "date_part",
  "date_subtract",
  "date_trunc",
  "extract",
  "isfinite",
  "justify_days",
  "justify_hours",
  "justify_interval",
  "localtime",
  "localtimestamp",
  "make_date",
  "make_interval",
  "make_time",
  "make_timestamp",
  "make_timestamptz",
  "now",
  "statement_timestamp",
  "timeofday",
  "timezone",
  "to_char",
  "to_date",
  "to_number",
  "to_timestamp",
  "transaction_timestamp",

  // String
  "ascii",
  "btrim",
  "char_length",
  "character_length",
  "chr",
  "concat",
  "concat_ws",
  "format",
  "initcap",
  "left",
  "length",
  "lower",
  "lpad",
  "ltrim",
  "octet_length",
  "overlay",
  "position",
  "quote_ident",
  "quote_literal",
  "quote_nullable",
  "repeat",
  "replace",
  "reverse",
  "right",
  "rpad",
  "rtrim",
  "split_part",
  "starts_with",
  "string_to_array",
  "string_to_table",
  "strpos",
  "substr",
  "substring",
  "translate",
  "trim",
  "upper",

  // Regexp
  "regexp_count",
  "regexp_instr",
  "regexp_like",
  "regexp_match",
  "regexp_matches",
  "regexp_replace",
  "regexp_split_to_array",
  "regexp_split_to_table",
  "regexp_substr",

  // Array / set-returning
  "array_append",
  "array_cat",
  "array_dims",
  "array_fill",
  "array_length",
  "array_lower",
  "array_ndims",
  "array_upper",
  "array_position",
  "array_positions",
  "array_prepend",
  "array_remove",
  "array_replace",
  "array_to_string",
  "cardinality",
  "generate_series",
  "generate_subscripts",
  "trim_array",
  "unnest",

  // Math
  "abs",
  "acos",
  "acosd",
  "asin",
  "asind",
  "atan",
  "atan2",
  "atan2d",
  "atand",
  "cbrt",
  "ceil",
  "ceiling",
  "cos",
  "cosd",
  "cot",
  "cotd",
  "degrees",
  "div",
  "exp",
  "factorial",
  "floor",
  "gcd",
  "lcm",
  "ln",
  "log",
  "log10",
  "min_scale",
  "mod",
  "pi",
  "power",
  "radians",
  "random",
  "round",
  "scale",
  "setseed",
  "sign",
  "sin",
  "sind",
  "sqrt",
  "tan",
  "tand",
  "trim_scale",
  "trunc",
  "width_bucket",

  // Conditional
  "coalesce",
  "greatest",
  "least",
  "nullif",

  // Encoding / hash / binary
  "decode",
  "encode",
  "md5",
  "get_bit",
  "get_byte",
  "set_bit",
  "set_byte",
  "sha224",
  "sha256",
  "sha384",
  "sha512",

  // Type conversion / inspection
  "cast",
  "pg_typeof",
  "format_type",

  // System information
  "current_catalog",
  "current_database",
  "current_query",
  "current_role",
  "current_schema",
  "current_schemas",
  "current_user",
  "inet_client_addr",
  "inet_client_port",
  "inet_server_addr",
  "inet_server_port",
  "pg_backend_pid",
  "pg_blocking_pids",
  "pg_current_snapshot",
  "pg_size_pretty",
  "pg_total_relation_size",
  "pg_relation_size",
  "pg_database_size",
  "pg_table_size",
  "pg_indexes_size",
  "session_user",
  "user",
  "version",

  // UUID / random helpers
  "gen_random_uuid",
]);

const FUNCTION_COMPLETIONS: readonly Completion[] = POSTGRES_FUNCTIONS.map(
  (name) => ({
    label: name,
    type: "function",
    apply: `${name}(`,
    boost: -1,
  })
);

/**
 * Completion source that adds PostgreSQL function names to the
 * autocomplete menu. Complements the dialect's keyword source and the
 * schema-based column/table source; the three stack as parallel
 * CompletionSources in the editor.
 */
export const postgresFunctionCompletion: CompletionSource =
  completeFromList(FUNCTION_COMPLETIONS);
